# this workflow is triggered on push to any push to any branch so that we can test the app on every canary release
name: 'Canary Release'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    name: Build Tauri Binaries
    timeout-minutes: 15

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.x.x

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Build mCal frontend
        run: pnpm build --filter=mcal

      # build tauri app
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload DMG artifact to macOS
        if: ${{ matrix.platform == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: MacOS (DMG)
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/dmg/*.dmg

      - name: Upload Deb artifact to linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: Linux Deb
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/deb/*.deb

      - name: Upload AppImage artifact to linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: Linux AppImage
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/deb/*.deb

      - name: Upload MSI artifact to Window
        if: ${{ matrix.platform == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: Windows MSI
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/msi/*.msi
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/nsis/*.exe


      - name: Upload NSIS artifact to Window
        if: ${{ matrix.platform == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: Windows NSIS
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/nsis/*.exe
