name: 'Publish mCal'

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Yangon"
          timezoneMac: "Asia/Yangon"
          timezoneWindows: "Myanmar Standard Time"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build

      - name: Unix like list files in dist directory
        if: ${{matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest' }}
        run: ls

      - name: Windows like list files in dist directory
        if: ${{matrix.platform == 'windows-latest'}}
        run: dir


      - name: Upload artifact to macOS
        if: ${{ matrix.platform == 'macos-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: MacOS (DMG)
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/dmg/*.dmg

      - name: Upload artifact to linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: Linux (DEB & AppImage)
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/deb/*.deb
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/appimage/*.AppImage

      - name: Upload artifact to Window
        if: ${{ matrix.platform == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: Windows (MSI & NSIS)
          path: |
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/msi/*.msi
            ./apps/myanmar_calendar/src-tauri/target/release/bundle/nsis/*.exe
